[INFO][2023-12-31 09:22:49,946][config_service.py:98]--{'config_file_name': '对外接口服务.xlsx', 'config_file_path': '对外接口服务.xlsx'}
[INFO][2023-12-31 09:23:22,438][config_service.py:98]--{'config_file_name': '前端功能页面.xlsx', 'config_file_path': '前端功能页面.xlsx'}
[ERROR][2023-12-31 20:07:24,739][generateAutoTestCases_service.py:155]--数据异常，请查看文档sheet页[前端功能页面配置]!
